nextcloud_mysql_user: nextcloud
nextcloud_mysql_password: "{{ lookup('passwordstore', pass_prefix + pass_name + '/mysql/' + nextcloud_mysql_user + ' create=true length=' + pass_generate_length ) }}"
nextcloud_mysql_database: nextcloud

nextcloud_admin_user: admin
nextcloud_admin_password: "{{ lookup('passwordstore', pass_prefix + pass_name + '/nextcloud/' + nextcloud_admin_user + ' create=true length=' + pass_generate_length ) }}"

nextcloud_installation_path: /var/www/html
nextcloud_version: "12.0.2"
nextcloud_sha256: "eb34d6cb9f55ee84bf2ad847b4b08cdb925321848ffa2264a9b1566e7b21a17c"

nextcloud_installation_path_safe: "{{nextcloud_installation_path|regex_replace('_','__')|regex_replace('/','_')}}"
