- name: Install aptitude
  apt: name=aptitude state=present
- name: Update and upgrade all packages
  apt: update_cache=yes autoremove=yes upgrade=yes
- name: Reboot system if required
  command: /usr/bin/systemd-run --on-active=2 /bin/systemctl reboot
    removes=/var/run/reboot-required
  ignore_errors: true
  async: 0
  poll: 0


