---
- name: Install DNS server
  hosts: dns-server
  roles:
    - dns-server

- name: Install authentication server
  hosts: authentication-server
  roles:
    - authentication-server

- name: Install mail server
  hosts: mail-server
  roles:
    - mail-server

- name: Install mailing-list server (Mailman 2)
  hosts: mailman2-server
  roles:
    - mailman2-server
