---
- hosts: hypervisors
  name: Set up hypervisors
  roles:
    - hypervisor
    - upgrade-reboot

- hosts: all:!hypervisors
  name: Install upgrades everywhere and reboot
  roles:
    - upgrade-reboot
