---
- name: Check local prerequisites
  hosts: all
  gather_facts: false
  run_once: True
  tasks:
    - name: Ensure Ansible version
      fail: msg="This playbook requires Ansible 2.3 or greater."
      when: ansible_version.major < 2 or (ansible_version.major == 2 and ansible_version.minor < 3)


- include: hypervisors.yml
- include: run-updates.yml
