---
- name: Check local prerequisites
  hosts: all
  gather_facts: false
  run_once: True
  tasks:
    - name: Ensure Ansible version
      fail: msg="This playbook requires Ansible 2.4 or greater."
      when: ansible_version.major < 2 or (ansible_version.major == 2 and ansible_version.minor < 4)
    - name: Ensure jmespath is installed (ignore debug output)
      debug:
        msg: "{{ [] | json_query('[]') }}"
      vars:
        ansible_become_pass: ""


- import_playbook: hypervisors.yml
- import_playbook: backend-infrastructure.yml
- import_playbook: database-setup.yml
- import_playbook: web-infrastructure.yml
- import_playbook: web-apps.yml
- import_playbook: misc-apps.yml
- import_playbook: zabbix.yml
- import_playbook: manage-users.yml
- import_playbook: manage-network.yml
- import_playbook: run-updates.yml
