---
- name: Basic install of frontend with letsencrypt
  hosts: web-frontend
  roles:
    - web-frontend
  tasks:
    - import_role:
        name: letsencrypt
        tasks_from: basic-install.yml
    - import_role:
        name: letsencrypt
        tasks_from: main-web.yml

