---
- name: Basic install of frontend
  hosts: web-frontend
  roles:
    - web-frontend.install

- name: Set up separate let's encrypt handler
  hosts: letsencrypt-handler
  roles:
    - letsencrypt.install

