---
- name: Set dynamic groups
  hosts: all
  gather_facts: false
  tasks:
  - name: Group Zabbix clients
    group_by:
      key: zabbix_client_{{ 'yes' if zabbix_server_name is defined else 'no' }}

- name: Install zabbix proxy
  hosts: zabbix-proxies
  roles:
    - zabbix-proxy

- name: Install zabbix agent
  hosts: zabbix_client_yes
  roles:
    - zabbix-agent
  vars:
    zabbix_link_templates_from_role: "{{ (zabbix_link_templates_proxy if inventory_hostname in (groups['zabbix-proxies']|default({})) else []) + (zabbix_link_templates_server if inventory_hostname in (groups['zabbix-server']|default({})) else []) }}"

