- name: Install software
  package:
    name: 'debconf-utils'
    state: 'present'

- name: Configure clamav-milter debconf
  debconf:
    name: clamav-milter
    question: 'clamav-milter/{{ item.question }}'
    value: '{{ item.value }}'
    vtype: '{{ item.vtype if "vtype" in item else "string" }}'
  with_items: "{{clamav_configuration}}"
  notify: Apply clamav-milter debconf

- name: Install software
  package:
    name: 'clamav-milter'
    state: 'present'

- name: Start and enable clamav-daemon
  service: name=clamav-daemon state=started enabled=true
- name: Enable clamav-milter
  service: name=clamav-milter enabled=true
  notify: restart clamav-milter

- name: Configure Postfix for milters
  postconf:
    config:
      milter_protocol: "2"
      milter_default_action: "accept"
      smtpd_milters__append: unix:var/run/clamav/clamav-milter.ctl
      non_smtpd_milters__append: unix:var/run/clamav/clamav-milter.ctl
  notify: restart postfix
