ode_user: ode
ode_user_home: "/home/{{ode_user}}"
ode_directory: "{{ode_user_home}}/ode"
ode_venv: "{{ode_directory}}/.venv"
ode_version: master
ode_instance: "{{ode_directory}}/instance"

ode_allow_direct_dn: True
ode_display_timezone: Europe/Berlin
ode_server_name: "ode.{{primary_domain}}"
ode_amu_mmapi_url: "http://{{hostvars[mail_server].internal_ip}}:8000/"

ode_ldap_service_user: ode
ode_ldap_service_password: "{{ lookup('passwordstore', pass_prefix + inventory_hostname + '/ldap/' + ode_ldap_service_user + ' create=true length=' + pass_generate_length ) }}"

ode_defaults:
  isi_event_sources: {}
