letsencrypt_handler_defaults:
  user: letsencrypt-handler
  acme_tiny_version: '4ed13950c0a9cf61f1ca81ff1874cde1cf48ab32'

letsencrypt_handler: {}

letsencrypt: {}

letsencrypt_defaults:
  delegated: false

ssl_directory: /etc/ssl
ssl_key_directory: "{{ssl_directory}}/private"
ssl_cert_directory: "{{ssl_directory}}/letsencrypt-out"
csr_subdir: "LE_{{ 'staging_' if account_data.staging else 'production_'}}{{account_data.email}}"
rsa_keysize: 4096

home: "/home/{{letsencrypt_handler_conf.user}}"
acme_path: "{{home}}/acme-tiny"

acme_challenge_directory: "/var/www/acme-challenge"  ## FIXME Compare web-frontend
