- name: Get libvirt network facts
  virt_net: command=facts

- name: "Shutdown domain {{libvirt_domain_delete}}"
  virt:
    name: "{{libvirt_domain_delete}}"
    command: shutdown
  ignore_errors: True

- name: "Stop and destroy domain {{libvirt_domain_delete}}"
  virt:
    name: "{{libvirt_domain_delete}}"
    state: destroyed
    autostart: false
  ignore_errors: "{{override_force_delete}}"

- name: "Undefine domain {{libvirt_domain_delete}}"
  virt:
    command: undefine
    name: "{{libvirt_domain_delete}}"
  ignore_errors: "{{override_force_delete}}"

- name: "Deconfigure DHCP lease for {{libvirt_domain_delete}}"
  command: |
    /bin/true
    {% for network in ansible_libvirt_networks %}
    {% for lease in ansible_libvirt_networks[network].dhcp_leases %}
    {% if lease.hostname|default("") == libvirt_domain_delete %}
    virsh net-update {{network|quote}} delete ip-dhcp-host "<host name='{{libvirt_domain_delete}}' />" --config --live
    {% endif %}
    {% endfor %}
    {% endfor %}
  ignore_errors: "{{override_force_delete}}"

- name: "Delete storage volume"
  command: virsh vol-delete --pool "{{libvirt_pool_name}}" "{{libvirt_domain_delete}}"
  ignore_errors: "{{override_force_delete}}"
