- name: Wait for system to come up
  wait_for_connection:

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - lvm2
    - rng-tools
    - libvirt-bin
    - qemu-kvm
    - libguestfs-tools
    - python-libvirt
    - python-lxml
    - dnsmasq-utils

- name: Set up volume group
  lvg:
    state: present
    vg: "{{ libvirt_vg_name }}"
    pvs: "{{ libvirt_vg_pvs }}"
  when: libvirt_vg_pvs is defined and libvirt_vg_pvs!=""

- name: Define storage pool
  virt_pool:
    name: "{{ libvirt_pool_name }}"
    autostart: yes
    state: present
    xml: "{{ lookup('template', 'pool.xml.j2')  }}"
  when: libvirt_vg_pvs is defined and libvirt_vg_pvs!=""

- name: Start storage pool
  virt_pool:
    name: "{{ libvirt_pool_name }}"
    autostart: yes
    state: active

- import_tasks: tasks/fix-libguestfs.yml

- include_tasks: tasks/list.yml

- name: Delete domains that are obsolete
  include_tasks: tasks/delete_domain.yml
  with_items: "{{ domains_deleted }}"
  loop_control:
    loop_var: libvirt_domain_delete
  when: libvirt_domain_delete in libvirt_all_domains or override_force_delete

- include_tasks: tasks/list.yml
  when: override_force_delete or libvirt_all_domains | intersect(domains_deleted)

- name: Install the port forward configuration directory
  file:
    path: "{{libvirt_port_forward_configuration_directory}}"
    state: directory

- name: Install network hook script
  copy:
    dest: "{{libvirt_port_forward_hook}}"
    src: 'qemu-hook.py'
    mode: 'a+x'

- name: "Setup virtual networking"
  import_tasks: tasks/setup_networks.yml

## NOTE: Only parameters set in domain_parameters get passed to the sub tasks
##  This is necessary to prevent ansible_ssh_common_args from causing a recursion loop
##  of nightmarish proportions. 
##  For reference: The error chain was:
##    ansible_ssh_common_args: "... destination_host ..."
##    destination_host: "{{libvirt_domain.inventory_hostname}}"
##    libvirt_domain: "{{domain_defaults|combine(domain_definition)}}"
##    domain_definition:
##      ...
##      ansible_ssh_common_args: "... destination_host ..."
##    destination_host: "{{libvirt_domain.inventory_hostname}}"
##    ... ad nauseam ...
##

- name: Setup domains that are missing
  include_tasks: tasks/setup_domain.yml
  with_items: "{{ hostvars | json_query(query_a) | select_keys(domain_parameters) }}"
  loop_control:
    loop_var: domain_definition
  when: domain_definition.inventory_hostname not in libvirt_all_domains
  vars:
    query_a: "*|[?hypervisor_machine=='{{inventory_hostname}}']"
    hypervisor_machine: "{{inventory_hostname}}"
    libvirt_domain: "{{domain_definition | default_hash(domain_defaults) }}"

- name: Update all domains
  include_tasks: tasks/update_domain.yml
  with_items: "{{ hostvars | json_query(query_a) | select_keys(domain_parameters) }}"
  loop_control:
    loop_var: domain_definition
  vars:
    query_a: "*|[?hypervisor_machine=='{{inventory_hostname}}']"
    hypervisor_machine: "{{inventory_hostname}}"
    libvirt_domain: "{{domain_definition | default_hash(domain_defaults) }}"

