- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - lvm2
    - rng-tools
    - libvirt-bin
    - qemu-kvm
    - libguestfs-tools
    - python-libvirt
    - python-lxml
    - dnsmasq-utils

- name: Set up volume group
  lvg:
    state: present
    vg: "{{ libvirt_vg_name }}"
    pvs: "{{ libvirt_vg_pvs }}"
  when: libvirt_vg_pvs is defined and libvirt_vg_pvs|length

- name: Define storage pool
  virt_pool:
    name: "{{ libvirt_pool_name }}"
    autostart: yes
    state: present
    xml: "{{ lookup('template', 'pool.xml.j2')  }}"

- name: Start storage pool
  virt_pool:
    name: "{{ libvirt_pool_name }}"
    autostart: yes
    state: active

- include: tasks/fix-libguestfs.yml

- include: tasks/list.yml

- name: Delete domains that are obsolete
  include: tasks/delete_domain.yml
  static: no
  with_items: "{{ libvirt_domains_deleted }}"
  loop_control:
    loop_var: libvirt_domain_delete
  when: libvirt_domain_delete in libvirt_all_domains or override_force_delete

- include: tasks/list.yml
  when: override_force_delete or libvirt_all_domains | intersect(libvirt_domains_deleted)

- name: Setup domains that are missing
  include: tasks/setup_domain.yml libvirt_domain={{libvirt_domain_defaults|combine(domain_definition)}}
  static: no
  with_items: "{{ libvirt_domains }}"
  loop_control:
    loop_var: domain_definition
  when: domain_definition.name not in libvirt_all_domains

- name: Set autostart property
  virt:
    name: "{{item.name}}"
    autostart: "{{(libvirt_domain_defaults|combine(item)).autostart}}"
    command: info  ## Need to provide a command, but not a state!, for "autostart" to be updated
  with_items: "{{ libvirt_domains }}"

- name: "Start domain"
  vars:
    libvirt_domain: "{{libvirt_domain_defaults|combine(domain_definition)}}"
  virt:
    name: "{{libvirt_domain.name}}"
    state: running
  with_items: "{{ libvirt_domains }}"
  loop_control:
    loop_var: domain_definition
  when: libvirt_domain.autostart

- name: "Wait for domain to come up"
  wait_for:
    host: "{{item.ip}}"
    port: 22
  with_items: "{{libvirt_domains}}"
  when: (libvirt_domain_defaults|combine(item)).autostart

# - name: Get libvirt network facts
#   virt_net: command=facts

## Network (re)definition is basically broken with the virt_net module
## Ignore it for now.  TODO
## User must set up network before use
#
# - name: Define network
#   virt_net:
#     name: "{{libvirt_net_name}}"
#     autostart: yes
#     state: present
#     xml: "{{ lookup('template', 'net.xml.j2')  }}"
