---
- name: Get libvirt network facts
  virt_net: command=facts

- name: Get libvirt nwfilter names
  shell: |
    virsh nwfilter-list | tail -n +3 | egrep -v ^$ | awk '{print $2;}'
  register: nwfilter_list
  changed_when: False

- name: Define nwfilter
  shell: |
    virsh nwfilter-define <( echo {{lookup('template', item + '.xml.j2')|quote}} )
  args:
    executable: /bin/bash
  when: item not in nwfilter_list.stdout_lines
  with_items:
    - allow-ipv6
    - clean-traffic-allow-ipv6

- debug:
    var: ansible_libvirt_networks

- name: Make sure the 'default' network is undefined
  virt_net:
    name: default
    state: absent
  when: libvirt_remove_default_network

- name: Define network
  virt_net:
    name: "{{network_name}}"
    state: present
    autostart: yes
    xml: "{{ lookup('template', 'net.xml.j2')  }}"
  with_dict: "{{ networks }}"
  vars:
    network_name: "{{item.key}}"
    network_definition: "{{item.value}}"

- name: Start network (because virt_net is stupid)
  virt_net:
    name: "{{item}}"
    state: active
  with_items: "{{networks}}"

- name: Set autostart (because virt_net is stupid)
  virt_net:
    name: "{{item}}"
    autostart: yes
  with_items: "{{networks}}"
