- name: Install mysql package
  package:
    name: mysql-server
    state: present

- name: Install MySQL-python for Ansible
  apt: name=python-mysqldb state=present
  when: ansible_os_family == 'Debian'

- name: Install python-mysqldb for Ansible
  yum: name=MySQL-python state=present
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Oracle Linux'

- name: Set MySQL root password
  command: mysqladmin -u root password "{{mysql_root_password}}"
  changed_when: False

- name: Emulate mysql_secure_installation
  command: 'mysql -p{{mysql_root_password}} -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
    - FLUSH PRIVILEGES
  changed_when: False
