- name: Install software
  package:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'postfix-policyd-spf-python'

- name: Have policyd-spf be started
  lineinfile:
    state: 'present'
    dest: '/etc/postfix/master.cf'
    regexp: '^\s*policyd-spf'
    line: 'policyd-spf  unix  -       n       n       -       0       spawn  user=policyd-spf argv=/usr/bin/policyd-spf'
  notify: restart postfix

- name: Set policyd-spf timeout, register SPF restriction
  postconf:
    config:
       policyd-spf_time_limit: "3600"
       smtpd_recipient_restrictions__append: "check_policy_service unix:private/policyd-spf"
  notify: restart postfix
