---
- name: Install basic packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - nginx

- name: Create configuration directories
  file:
    path: /etc/nginx/snippets
    state: directory

- name: Generate custom DH parameters
  command: openssl dhparam 4096 -out /etc/nginx/dhparam.pem
  args: 
    creates: /etc/nginx/dhparam.pem

- name: Install configuration snippets
  template:
    dest: /etc/nginx/snippets/{{item}}
    src: "{{item}}.j2"
  with_items:
    - acme.conf
    - ssl.conf

- name: "Call CSR generation"
  include_role:
    name: letsencrypt.generate_csr
  static: no
  with_items: "{{hostvars|json_query(query_a) | map('default_hash', web_defaults ) | list | json_query(query_b)}}"
  loop_control:
    loop_var: domain
  vars:
    query_a: "*.web[]"
    query_b: "[?frontend=={{inventory_hostname}}].{name:name,aliases:aliases}"
    destination_host: "{{inventory_hostname}}"
