- name: Create directory
  file:
    path: "{{letsencrypt_account_base}}"
    state: directory
  vars:
    letsencrypt_account_base: "{{acme_path}}/LE_{{ 'staging_' if account_data.staging else 'production_'}}{{account_data.email}}"
    home: "/home/{{letsencrypt_handler_conf.user}}"  ## FIXME: Would really like to query this, alternatively: set
    acme_path: "{{home}}/acme-tiny"  ## FIXME: Duplicate, also: stupid

- name: Create account key
  command: 'openssl genrsa -out "{{account_key_file}}"  4096'
  args:
    creates: "{{account_key_file}}"
  vars:
    account_key_file: "{{letsencrypt_account_base}}.key"
    letsencrypt_account_base: "{{acme_path}}/LE_{{ 'staging_' if account_data.staging else 'production_'}}{{account_data.email}}"
    home: "/home/{{letsencrypt_handler_conf.user}}"
    acme_path: "{{home}}/acme-tiny"

- name: Install renew script
  template:
    dest: '{{dirs.acme}}/do_renew.sh'
    src: 'do_renew.sh.j2'
    mode: 'a+x'
  vars:
    home: "/home/{{letsencrypt_handler_conf.user}}"
    dirs:
      acme: "{{home}}/acme-tiny"
      challenge: "{{home}}/acme-challenge"
      certificates: "{{home}}/public_html"

- debug:
    var: letsencrypt_csrs

