- name: Install prerequisites
  apt: state=present name={{item}}
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - python-virtualenv
    - git
    - rabbitmq-server
    - acl  ## Set HACK HACK HACK below

- name: Set up LDAP service user
  include_role:
    name: authentication-server
    tasks_from: setup-service-user
    allow_duplicates: true
  vars:
    service_user: "{{ode_ldap_service_user}}"
    service_password: "{{ode_ldap_service_password}}"
    destination_host: "{{ldap_server}}"
  delegate_to: "{{ldap_server}}"

- name: Create a dedicated ode user
  user:
    name: "{{ode_user}}"
    home: "{{ode_user_home}}"
    state: present

- name: Remount /tmp with acl support (HACK HACK HACK)
  command: mount / -o remount,acl
  changed_when: false
  args:
    warn: false

- name: Download/Update ode
  git:
    clone: yes
    dest: "{{ode_directory}}"
    repo: https://github.com/henryk/ode.git
    update: yes
    version: "{{ode_version}}"
  become_user: "{{ode_user}}"

- name: Upgrade setuptools/pip via pip
  pip:
    state: latest
    name: "{{item}}"
    virtualenv: "{{ode_venv}}"
    chdir: "{{ode_directory}}"
  become_user: "{{ode_user}}"
  with_items:
    - pip
    - setuptools

- name: Install base requirements via pip
  pip:
    requirements: "requirements.txt"
    state: latest
    virtualenv: "{{ode_venv}}"
    chdir: "{{ode_directory}}"
  become_user: "{{ode_user}}"

- name: Install additional requirements via pip
  pip:
    name: gunicorn
    state: latest
    virtualenv: "{{ode_venv}}"
    chdir: "{{ode_directory}}"
  become_user: "{{ode_user}}"

- name: Create instance directory
  file:
    state: directory
    owner: "{{ode_user}}"
    group: "{{ode_user}}"
    path: "{{ode_instance}}"

- name: Install ODE configuration
  template:
    dest: "{{ode_instance}}/settings.py"
    owner: "{{ode_user}}"
    group: "{{ode_user}}"
    mode: "0600"
    src: "templates/settings.py.j2"
  notify:
    - restart ode

- name: Upgrade database
  shell: |
    source {{ode_venv|quote}}/bin/activate
    PYTHON_PATH=.:${PYTHON_PATH} ./manage.py db upgrade head
  args:
    chdir: "{{ode_directory}}"
    executable: /bin/bash 
  become_user: "{{ode_user}}"

- name: Install ODE service file
  template:
    dest: "/etc/systemd/system/ode.service"
    src: "templates/ode.service.j2"
  notify:
    - restart ode

- name: Enable and start ODE service
  systemd:
    daemon_reload: yes
    name: ode
    enabled: yes
  notify:
    - restart ode
