- name: Generate zabbix proxy PSK
  local_action: "shell pass list {{zabbix_psk_key}} > /dev/null || ( ( xxd -c 32 -l 32 -p /dev/urandom; echo -n 'id: '; xxd -c 10 -l 10 -p /dev/urandom ) | pass insert -m {{ zabbix_psk_key }} )"
  vars:
    ansible_become: False
  register: zabbix_generate_psk
  changed_when: '"is not in the password store" in zabbix_generate_psk.stderr'

- name: Install zabbix proxy for Debian based systems
  include: debian.yml
  static: no
  when: ansible_os_family == 'Debian' and zabbix_server is defined

# FIXME: RedHat

- name: Configure zabbix proxy on the server
  local_action:
    module: zabbix_proxy
    server_url: "http://{{zabbix_server}}/zabbix/"
    login_user: "{{zabbix_server_user}}"
    login_password: "{{zabbix_server_password}}"
    name: "{{zabbix_hostname}}"
    mode: active
    state: present
    tls_connect: "PSK"
    tls_accept: ["PSK"]
    tls_psk_identity: "{{ zabbix_psk_id }}"
    tls_psk: "{{ zabbix_psk }}"
  vars:
    ansible_become: False
