---
- name: Install required packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - slapd
    - ldap-utils
    - debconf-utils

- name: Check for initial configuration
  stat:
    path: '/etc/ldap'
  register: ldap_exists

- name: Perform initial configuration
  include_tasks: "tasks/initial-install.yml"
  when: ldap_reinitialize or ldap_exists.stat.exists


