---
- name: Install required packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - ldap-utils
    - debconf-utils
    - python-ldap

- name: Check for initial configuration
  stat:
    path: '/etc/ldap/schema'
  register: ldap_exists

- name: Perform initial configuration
  include_tasks: "tasks/initial-install.yml"
  when: ldap_reinitialize or not ldap_exists.stat.exists

- name: Make sure LDAP server (slapd) is enabled and started
  systemd:
    name: slapd
    state: started
    enabled: yes

- name: Create hierarchies
  ldap_entry:
    bind_dn: "{{ldap_root_dn}}"
    bind_pw: "{{ldap_root_password}}"
    dn: ou={{item}},{{ ldap_domain | hostname_to_dn}}
    objectClass:
      - organizationalUnit
      - top
    attributes:
      ou: "{{item}}"
  with_items:
    - "{{ldap_users_ou}}"
    - "{{ldap_groups_ou}}"
    - "{{ldap_services_ou}}"
    - "{{ldap_mailing_lists_ou}}"
    - "{{ldap_aliases_ou}}"
    - "{{ldap_access_rights_ou}}"

- name: Create privileged groups
  ldap_entry:
    bind_dn: "{{ldap_root_dn}}"
    bind_pw: "{{ldap_root_password}}"
    dn: cn={{item}},ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}
    objectClass:
      - groupOfNames
      - top
    attributes:
      cn: "{{item}}"
      member: "{{ldap_dummy_dn}}"
  with_items: "{{ldap_full_access_groups + ldap_read_member_list_groups}}"

- name: Create access rights
  ldap_entry:
    bind_dn: "{{ldap_root_dn}}"
    bind_pw: "{{ldap_root_password}}"
    dn: ou={{item}},ou={{ldap_access_rights_ou}},{{ ldap_domain | hostname_to_dn}}
    objectClass:
      - organizationalUnit
      - top
    attributes:
      ou: "{{item}}"
  with_items:
    - "{{ldap_access_right_mail}}"


- name: Set ACL
  ldap_attr:
    dn: "olcDatabase={1}mdb,cn=config"
    name: olcAccess
    state: exact
    values: ## FIXME uid=dovecot hardcoded
      - >-
        {0}to attrs=userPassword
        by self write
        by anonymous auth
        {% for g in ldap_full_access_groups %} by group.exact="cn={{g}},ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}" write {% endfor %}
        by dn.exact="uid=dovecot,ou={{ldap_services_ou}},{{ ldap_domain | hostname_to_dn}}" read
        by * none
      - >-
        {1}to attrs=shadowLastChange
        by self write
        {% for g in ldap_full_access_groups %} by group.exact="cn={{g}},ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}" write {% endfor %}
        by dn.children="ou={{ldap_services_ou}},{{ ldap_domain | hostname_to_dn}}" read
        by * none
      - >-
        {2}to dn.children="ou={{ldap_users_ou}},{{ ldap_domain | hostname_to_dn}}" attrs=cn,sn,givenName
        by self write
        {% for g in ldap_full_access_groups %} by group.exact="cn={{g}},ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}" write {% endfor %}
        {% for g in ldap_read_member_list_groups %} by group.exact="cn={{g}},ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}" read {% endfor %}
        by dn.children="ou={{ldap_services_ou}},{{ ldap_domain | hostname_to_dn}}" read
      - >-
        {3}to dn.subtree="ou={{ldap_users_ou}},{{ ldap_domain | hostname_to_dn}}" attrs=objectClass,uid,entry,memberOf,CC-preferredMail
        by self read
        {% for g in ldap_full_access_groups %} by group.exact="cn={{g}},ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}" write {% endfor %}
        {% for g in ldap_read_member_list_groups %} by group.exact="cn={{g}},ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}" read {% endfor %}
        by dn.children="ou={{ldap_services_ou}},{{ ldap_domain | hostname_to_dn}}" read
      - >-
        {4}to dn.base=""
        by * read
      - >-
        {5}to dn.subtree="ou={{ldap_mailing_lists_ou}},{{ ldap_domain | hostname_to_dn}}"
        {% for g in ldap_full_access_groups %} by group.exact="cn={{g}},ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}" write {% endfor %}
        by dn.children="ou={{ldap_services_ou}},{{ ldap_domain | hostname_to_dn}}" write
      - >-
        {7}to dn.subtree="ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}" attrs=objectClass,cn,member,entry
        {% for g in ldap_full_access_groups %} by group.exact="cn={{g}},ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}" write {% endfor %}
        {% for g in ldap_read_member_list_groups %} by group.exact="cn={{g}},ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}" read {% endfor %}
        by dn.children="ou={{ldap_services_ou}},{{ ldap_domain | hostname_to_dn}}" read
      - >-
        {8}to *
        {% for g in ldap_full_access_groups %} by group.exact="cn={{g}},ou={{ldap_groups_ou}},{{ ldap_domain | hostname_to_dn}}" write {% endfor %}
        by dn.children="ou={{ldap_services_ou}},{{ ldap_domain | hostname_to_dn}}" read
        by self read
