ansible_outgoing_user: "{{ ansible_user if ansible_user is defined else lookup('pipe', 'whoami') }}"

libvirt_vg_name: "{{ inventory_hostname }}"
libvirt_pool_name: "{{libvirt_vg_name}}"
libvirt_net_name: default
libvirt_net_device: virbr0
libvirt_net_ip_base: 192.168.155.1
libvirt_net_ip_mask: 255.255.255.0
libvirt_net_ip_dhcp_min: 192.168.155.200
libvirt_net_ip_dhcp_max: 192.168.155.254

virt_builder_options:
  all: --update --root-password disabled
  ubuntu: ""
  fedora: --selinux-relabel

virt_builder_install:
  all:
    - mc
    - screen
    - rng-tools
    - openssh-server
    - qemu-guest-agent
  ubuntu:
    - python
    - aptitude
    - python-apt
    - perl-modules
  fedora:
    - python2
    - python2-dnf
    - libselinux-python

virt_builder_admin_groups:
  all: []
  ubuntu:
    - sudo
    - adm
  fedora:
    - wheel

virt_builder_users: "{{ users }}"
virt_builder_user_defaults:
  is_admin: False
  shell: /bin/bash
  ssh_keys: []
  groups: []

libvirt_domain_defaults:
  distribution: ubuntu-16.04
  disksize: 5G
  memsize: 524288
  cpus: 1
  autostart: yes
  groups: []
  virt_builder_install: []
  virt_builder_options: ""
  virt_builder_users: "{{ virt_builder_users }}"

libvirt_domains: []
libvirt_domains_deleted: []

override_force_delete: false