- name: Download nextcloud
  get_url: 
    dest: '{{nextcloud_installation_path}}/nextcloud.tar.bz2'
    url: 'https://download.nextcloud.com/server/releases/nextcloud-{{nextcloud_version}}.tar.bz2'
    checksum: 'sha256:{{nextcloud_sha256}}'

- name: Unpack nextcloud
  unarchive:
    dest: '{{nextcloud_installation_path}}'
    src: '{{nextcloud_installation_path}}/nextcloud.tar.bz2'
    remote_src: true
    extra_opts:
      - '--strip-components=1'

- name: Delete downloaded archive
  file:
    path: '{{nextcloud_installation_path}}/nextcloud.tar.bz2'
    state: absent

- name: Change ownership
  file:
    path: "{{nextcloud_installation_path}}"
    owner: "www-data"
    group: "www-data"
    recurse: "yes"
    state: "directory"

- name: Run installation
  shell: |
    cd "{{nextcloud_installation_path}}"
    php occ  maintenance:install --database "mysql" --database-name "{{nextcloud_mysql_database}}"  --database-user "{{nextcloud_mysql_user}}" --database-pass "{{nextcloud_mysql_password}}" --admin-user "{{nextcloud_admin_user}}" --admin-pass "{{nextcloud_admin_password}}"
  become_user: "www-data"
