- name: Install base packages
  apt: state=present name={{item}}
  with_items:
    - apache2
    - php
    - libapache2-mod-php7.0
    - php7.0-gd
    - php7.0-json
    - php7.0-mysql
    - php7.0-curl
    - php7.0-mbstring
    - php7.0-intl
    - php7.0-mcrypt
    - php-imagick
    - php7.0-xml
    - php7.0-zip
    - php-redis
    - php-apcu
    - acl  ## See HACK HACK HACK in initial-install
  notify:
    - restart apache2

- name: Remount /tmp with acl support (HACK HACK HACK)
  command: mount / -o remount,acl
  changed_when: false
  args:
    warn: false

- name: Set up DB
  include_role:
    name: mysql-server
    tasks_from: setup-db
    allow_duplicates: true
  vars:
    mysql_setup_db_user: "{{nextcloud_mysql_user}}"
    mysql_setup_db_password: "{{nextcloud_mysql_password}}"
    mysql_setup_db_database: "{{nextcloud_mysql_database}}"
    mysql_setup_db_encoding: "utf8mb4"
    mysql_setup_db_collation: "utf8mb4_general_ci"

- name: Activate mod_rewrite and others
  apache2_module:
    name: "{{item}}"
    state: present
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
  notify:
    - restart apache2

- name: Activate PHP opcache
  ini_file:
    path: /etc/php/7.0/apache2/php.ini
    section: opcache
    state: present
    option: "opcache.{{item.key}}"
    value: "{{item.value}}"
  with_dict:
    enable: 1
    enable_cli: 1
    interned_strings_buffer: 8
    max_accelerated_files: 10000
    memory_consumption: 128
    save_comments: 1
    revalidate_freq: 1
  notify:
    - restart apache2

- name: Allow .htaccess override (1/2)
  copy:
    content: |
      <Directory {{nextcloud_installation_path}}/>
        Options +FollowSymlinks
        AllowOverride All

        <IfModule mod_dav.c>
          Dav off
        </IfModule>

        SetEnv HOME {{nextcloud_installation_path}}
        SetEnv HTTP_HOME {{nextcloud_installation_path}}

      </Directory>
    dest: "/etc/apache2/conf-available/nextcloud_{{nextcloud_installation_path_safe}}.conf"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - restart apache2

- name: Allow .htaccess override (2/2)
  file:
    src: '/etc/apache2/conf-available/nextcloud_{{nextcloud_installation_path_safe}}.conf'
    dest: '/etc/apache2/conf-enabled/nextcloud_{{nextcloud_installation_path_safe}}.conf'
    owner: 'root'
    group: 'root'
    state: link
  notify:
    - restart apache2

- name: Create nextcloud directory
  file:
    dest: '{{nextcloud_installation_path}}'
    state: directory

- name: Check for initial installation
  stat:
    path: '{{nextcloud_installation_path}}/cron.php'
  register: cron_php

- name: Run initial installation
  include: tasks/initial-install.yml
  static: no
  when: not cron_php.stat.exists

- name: Install cron job
  cron:
    minute: '*/15'
    user: www-data
    job: "php -f {{nextcloud_installation_path}}/cron.php"
    state: present
    name: "Nextcloud regular cron job"

- name: Configure nextcloud to use cron
  shell: |
    cd "{{nextcloud_installation_path}}"
    if [ $(php occ config:app:get core backgroundjobs_mode) != "cron" ]; then
      php occ background:cron
    fi
  become_user: "www-data"
  register: set_background_mode
  changed_when: "'cron' in set_background_mode.stdout"

## FIXME Configure trusted domains
- name: Get trusted domains
  shell: |
    cd "{{nextcloud_installation_path}}"
    php occ config:system:get trusted_domains
  become_user: "www-data"
  register: trusted_domains
  changed_when: false

- name: Configure nextcloud for domain and base URL
  shell: |
    cd "{{nextcloud_installation_path}}"
    if [ $(php occ config:system:get htaccess.RewriteBase) != "/" ]; then
      php occ config:system:set htaccess.RewriteBase --value '/'
      php occ maintenance:update:htaccess
    fi
  become_user: "www-data"
  register: set_domain
  changed_when: "'RewriteBase' in set_domain.stdout"

- name: Configure nextcloud to use redis and APCu
  shell: |
    cd "{{nextcloud_installation_path}}"
    md5sum config/config.php
    php occ config:system:set redis host --value 'localhost' || exit 1
    php occ config:system:set redis port --type integer --value 6379 || exit 1
    php occ config:system:set memcache.local --value '\OC\Memcache\APCu' || exit 1
    php occ config:system:set memcache.locking --value '\OC\Memcache\Redis' || exit 1
    md5sum config/config.php
  become_user: "www-data"
  register: configure_nextcloud_redis
  changed_when: configure_nextcloud_redis.stdout_lines[0] != configure_nextcloud_redis.stdout_lines[-1]
