---
- name: Install basic packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - cron
    - git
    - acl
    - openssl 

- name: Create directories
  file: path={{item.directory}} state=directory mode={{item.mode}}
  with_items:
    - { directory: "{{ssl_directory}}", mode: "a+rX" }
    - { directory: "{{ssl_key_directory}}", mode: "0600" }

- include: tasks/install-handler.yml letsencrypt_handler_conf="{{letsencrypt_handler_defaults|combine(letsencrypt_handler)}}"

- name: "Call CSR generation"
  include: tasks/generate-csr.yml letsencrypt_handler_conf="{{letsencrypt_handler_defaults|combine(letsencrypt_handler)}}"
  static: no
  with_items: "{{hostvars|json_query(query_a) | map('default_hash', {'letsencrypt': {}} ) | map('default_hash', letsencrypt, 'letsencrypt' ) | list | json_query(query_b)}}"
  loop_control:
    loop_var: domain
  vars:
    query_a: "*.web[?frontend=='{{inventory_hostname}}'][]"
    query_b: "[].{name:name,aliases:aliases,frontend:frontend,letsencrypt:letsencrypt}"

- include: tasks/setup-handler.yml letsencrypt_handler_conf="{{letsencrypt_handler_defaults|combine(letsencrypt_handler)}}"
  static: no

  with_items: "{{ hostvars | json_query(query_a) | map('default_hash', letsencrypt) | list | json_query(query_b) }}"
  loop_control:
    loop_var: account_data
  vars:
    query_a: "*.web[?frontend=='{{inventory_hostname}}'][].letsencrypt"
    query_b: "[].{staging:staging, email:email}[]"

