zabbix_server_user: Admin
zabbix_hostname: "{{inventory_hostname}}"
zabbix_psk_key: "{{ pass_prefix + pass_name + '/_zabbix-agent-psk' }}"
zabbix_psk: "{{ lookup('passwordstore', zabbix_psk_key ) }}"
zabbix_psk_id: "{{ lookup('passwordstore', zabbix_psk_key + ' subkey=id' ) }}"
zabbix_psk_file: "/etc/zabbix/zabbix_agentd.psk"

zabbix_host_groups:
  - "Linux servers"

zabbix_link_templates_from_role: []

zabbix_link_templates_actual: "{{ zabbix_link_templates + zabbix_link_templates_from_role }}"

zabbix_link_templates: "{{ zabbix_link_templates_additional + zabbix_link_templates_default }}" # For *overwriting* in individual hosts

zabbix_link_templates_additional: [] # For *adding* in individual hosts

zabbix_link_templates_default:
  - "Template OS Linux"

zabbix_link_templates_proxy:
  - "Template App Zabbix Proxy"

zabbix_link_templates_server:
  - "Template App Zabbix Server"

# TODO Somehow get this from the inventory
zabbix_proxy_ip: "{{zabbix_proxy if zabbix_proxy is defined else ''}}"
