- name: Install local list of forbidden domains
  copy:
    content: |
      foxmail.com REJECT We won't accept mail from foxmail.com, it's always spam. Sorry.
    dest: '/etc/postfix/sender_access'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - update sender_access


- name: Configure Postfix restrictions
  postconf:
    config:
      smtpd_recipient_restrictions__prepend:
        - "permit_dnswl_client list.dnswl.org"
        - "permit_dnswl_client neighbours.ploetzli.ch=127.0.0.2"
        - "check_sender_access hash:/etc/postfix/sender_access"
      smtpd_recipient_restrictions__append:
        - "reject_rhsbl_helo dbl.spamhaus.org"
        - "reject_rhsbl_sender dbl.spamhaus.org"
      smtpd_client_restrictions__prepend:
        - "permit_dnswl_client list.dnswl.org"
        - "permit_dnswl_client neighbours.ploetzli.ch=127.0.0.2"
      smtpd_client_restrictions__append:
        - "reject_rbl_client zen.spamhaus.org"
        - "reject_rbl_client bl.spamcop.net"
        - "reject_rbl_client cbl.abuseat.org"
        - "reject_rhsbl_client dbl.spamhaus.org"
        - "reject_rbl_client ix.dnsbl.manitu.net"
  notify:
    - restart postfix
